twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        supported_locales: '%app.supported_locales%'
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true


    